authorName: default
experimentName: gwd
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 50
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python3 nni_accm_traing.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
